name: deploy lambda
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build docker images
        run: docker build -t local - < ./.github/workflows/Dockerfile

      - name: Build app
        run: docker run -v $PWD:/srv -w/srv local bash -c "cd /srv/go/src && bash api/local/build.sh"

      - name: Deploy app
        run: |
          cd go/src
          echo "${{ secrets.AWS_SERVER_KEY }}" > key.pem
          chmod 600 ./key.pem
          scp -i "./key.pem"  -o StrictHostKeyChecking=no ./deployment.zip ${{ vars.AWS_SERVER_USER }}@${{ vars.AWS_SERVER_IP }}:~
          ssh -i "./key.pem" ${{ vars.AWS_SERVER_USER }}@${{ vars.AWS_SERVER_IP }} "unzip -o deployment.zip"
          ssh -i "./key.pem" ${{ vars.AWS_SERVER_USER }}@${{ vars.AWS_SERVER_IP }} "fuser -k 8980/tcp || true"
          ssh -i "./key.pem" ${{ vars.AWS_SERVER_USER }}@${{ vars.AWS_SERVER_IP }} "./main > /var/log/citydream-api 2>&1 &"
