name: deploy lambda
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build docker images
        run: docker build -t local - < ./.github/workflows/Dockerfile

      - name: Build app
        run: docker run -v $PWD:/srv -w/srv local bash -c "cd /srv/go/src && bash api/local/build.sh"

      - name: Deploy app
        env:
          AWS_SERVER_KEY: ${{ secrets.AWS_SERVER_KEY }}
          AWS_SERVER_IP: ${{ secrets.AWS_SERVER_IP }}
          AWS_SERVER_USER: ${{ secrets.AWS_SERVER_USER }}
        run: |
          cd go/src
          echo $AWS_SERVER_KEY > key.pem
          scp -i "./key.pem" ./deployment.zip ${AWS_SERVER_USER}@${AWS_SERVER_IP}:~
          ssh -i "./key.pem" ${AWS_SERVER_USER}@${AWS_SERVER_IP} "unzip deployment.zip"
